### PR TITLE
fix[#23] detect failure and report to user

### LINKED ISSUE #23: bug: the utility shows install succeeded even when it fails installing the package

### PR DESCRIPTION
**Pull request by jardon**
- repurpose SideloaderInstallDone to handle failure
- remove dedicated fail ui
image

closes #23

### CODE REVIEW

**Comment by jardon** [comment]
i dont think this can be done until [this](https://github.com/Vanilla-OS/vanilla-system-operator/issues/159) gets fixed.  since vso always reports a success, the vte terminal status is inaccurate.

**Comment by jardon** [comment]
This may be sufficient as-is, but i need to test it more.  If the exit code is reported correctly, it should work as expected.

**Comment by jardon** [comment]
@mirkobrombin do you know if the VTE terminal checks in the users $PATH for the subprocess?  i have an [upstream change](https://github.com/Vanilla-OS/vanilla-system-operator/pull/160) from `vso` installed locally in `~/.local`, but it appears its returning a `0` status code.

**Comment by mirkobrombin** [comment]
VTE itself does not, it expect `PATH` to be set, which I think is the case. What happen if you hard code a `echo $PATH` and run VTE?

**Comment by jardon** [comment]
this does behave correctly with the upstream fix.  ive rebased and it should be ready to merge,  but it wont display an error was detected until that `vso` change is included in a new release.

**Review by mirkobrombin — APPROVED** [review]
LGTM

**Pull request merged**
